name: Update example images
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Update the example on the README
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ./
        with:
          feed_urls: "https://dev.to/feed/mpetry"
          max_posts_per_url: 5
          position_indicator: "post-list"
          locale: "pt-BR"
          time_zone: "America/Sao_Paulo"
          output_dir: "generated_files"
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated content
          skip_checkout: true
